### ISSUE TITLE
Replacement of Create-Slider with Struct-Copy

### ISSUE THREAD

**Issue by JoshSanch** [Viviose/Risk#4]
Common sense in the Racket language implores us to change the content of structs using struct-copy rather than creating a new struct with one or two changed values.
- Creates clarity of programming
- Prevents issues arising from changes in the struct

These instances of create-slider should be replaced with struct-copy calls.

**Comment by pattyjogal** [comment]
We decided that because I had a create-slider function in place, that a struct copy would not apply to this case.

**Comment by JoshSanch** [comment]
poser
